version: '3.3'

services:
  database:
    image: mysql:5.7
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  wordpress:
    image: wordpress:latest
    depends_on:
      - database
    ports:
      # Expose both HTTP and HTTPS
      - "8080:80"
      - "8443:443"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

volumes:
  wordpress_data: {}